import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F0F14',
  },
  flex1: {
    flex: 1,
  },

  // Modern Login Screen Styles
  loginScrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  loginContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 40,
  },
  loginHeader: {
    alignItems: 'center',
    marginBottom: 48,
  },
  loginTitle: {
    fontSize: 48,
    fontWeight: '800',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: '#FFFFFF',
    marginBottom: 12,
    letterSpacing: -1,
  },
  loginSubtitle: {
    fontSize: 18,
    color: '#9CA3AF',
    textAlign: 'center',
    fontWeight: '500',
  },
  loginForm: {
    marginBottom: 32,
  },
  inputGroup: {
    marginBottom: 24,
  },
  inputLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#E5E7EB',
    marginBottom: 8,
    marginLeft: 4,
  },
  loginInput: {
    backgroundColor: '#1F1F26',
    borderWidth: 1.5,
    borderColor: '#374151',
    borderRadius: 16,
    padding: 18,
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '500',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  authButton: {
    backgroundColor: '#8B5CF6',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  authButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  toggleAuthButton: {
    alignItems: 'center',
    marginBottom: 16,
    paddingVertical: 8,
  },
  toggleAuthText: {
    color: '#8B5CF6',
    fontSize: 16,
    fontWeight: '600',
  },
  forgotPasswordButton: {
    alignItems: 'center',
    marginBottom: 32,
    paddingVertical: 8,
  },
  forgotPasswordText: {
    color: '#F59E0B',
    fontSize: 14,
    fontWeight: '600',
  },
  skipSection: {
    marginBottom: 32,
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 24,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#374151',
  },
  dividerText: {
    marginHorizontal: 16,
    color: '#6B7280',
    fontSize: 14,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  skipButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#374151',
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
  },
  skipButtonText: {
    color: '#9CA3AF',
    fontSize: 16,
    fontWeight: '600',
  },
  loginFooter: {
    alignItems: 'center',
    marginTop: 24,
  },
  footerText: {
    color: '#6B7280',
    fontSize: 12,
    textAlign: 'center',
    lineHeight: 18,
  },

  // Welcome Screen Styles
  welcomeContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    backgroundColor: '#0F0F14',
  },
  welcomeTitle: {
    fontSize: 52,
    fontWeight: '900',
    color: '#FFFFFF',
    marginBottom: 16,
    textAlign: 'center',
    letterSpacing: -1.5,
  },
  welcomeSubtitle: {
    fontSize: 28,
    color: '#8B5CF6',
    marginBottom: 24,
    textAlign: 'center',
    fontWeight: '700',
  },
  welcomeDescription: {
    fontSize: 18,
    color: '#9CA3AF',
    textAlign: 'center',
    marginBottom: 40,
    lineHeight: 28,
    fontWeight: '500',
  },
  features: {
    marginBottom: 48,
    alignItems: 'center',
  },
  featureText: {
    fontSize: 16,
    color: '#34D399',
    marginBottom: 12,
    textAlign: 'center',
    fontWeight: '600',
  },

  // Modern Workout Screen Header
  workoutHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: 24,
    paddingTop: 16,
    backgroundColor: '#0F0F14',
  },
  profileButton: {
    backgroundColor: 'rgba(139, 92, 246, 0.2)',
    borderRadius: 20,
    width: 56,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.3)',
  },
  profileButtonText: {
    fontSize: 24,
    color: '#8B5CF6',
  },
  dateText: {
    fontSize: 16,
    color: '#9CA3AF',
    marginBottom: 6,
    fontWeight: '500',
  },
  welcomeBack: {
    fontSize: 28,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.5,
  },

  // Modern Today's Workout Card
  todayCard: {
    backgroundColor: '#1F1F26',
    margin: 20,
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: '#374151',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  todayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  todayTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  addText: {
    fontSize: 14,
    color: '#8B5CF6',
    fontWeight: '600',
    backgroundColor: 'rgba(139, 92, 246, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  todayContent: {
    fontSize: 16,
    color: '#9CA3AF',
    lineHeight: 24,
    fontWeight: '500',
  },
  todayExercisesList: {
    marginTop: 16,
  },
  todayExerciseItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(139, 92, 246, 0.1)',
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.2)',
  },
  exerciseInfo: {
    flex: 1,
  },
  exerciseName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  exerciseDetails: {
    fontSize: 14,
    color: '#9CA3AF',
    fontWeight: '500',
  },
  removeButton: {
    backgroundColor: '#EF4444',
    borderRadius: 12,
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
  },
  removeButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '700',
  },

  // Modern Action Buttons
  mainButtons: {
    paddingHorizontal: 20,
    marginBottom: 32,
    gap: 12,
  },
  
  generateButton: {
    backgroundColor: '#6366F1',
    borderRadius: 20,
    padding: 24,
    alignItems: 'center',
    marginBottom: 12,
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.2)',
  },
  generateIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  generateButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
    letterSpacing: 0.3,
  },
  generateSubtext: {
    color: 'rgba(255, 255, 255, 0.75)',
    fontSize: 13,
    fontWeight: '500',
  },

  llmButton: {
    backgroundColor: '#059669',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    marginBottom: 12,
    shadowColor: '#059669',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 6,
  },
  llmIcon: {
    fontSize: 20,
    marginBottom: 6,
  },
  llmButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 2,
  },
  llmSubtext: {
    color: 'rgba(255, 255, 255, 0.75)',
    fontSize: 12,
    fontWeight: '500',
  },

  programsButton: {
    backgroundColor: '#D97706',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#D97706',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 6,
  },
  programsIcon: {
    fontSize: 20,
    marginBottom: 6,
  },
  programsButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 2,
  },
  programsSubtext: {
    color: 'rgba(255, 255, 255, 0.75)',
    fontSize: 12,
    fontWeight: '500',
  },

  // Modern Stats Cards
  quickStats: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginBottom: 24,
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#1F1F26',
    borderRadius: 20,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#374151',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 6,
    minHeight: 80,
    justifyContent: 'center',
  },
  statNumber: {
    fontSize: 20,
    fontWeight: '800',
    color: '#8B5CF6',
    marginBottom: 4,
    textAlign: 'center',
  },
  statLabel: {
    fontSize: 10,
    color: '#9CA3AF',
    textTransform: 'uppercase',
    fontWeight: '600',
    letterSpacing: 0.3,
    textAlign: 'center',
    lineHeight: 12,
  },

  // Modern Last Workout Card
  lastWorkoutCard: {
    backgroundColor: 'rgba(139, 92, 246, 0.1)',
    margin: 20,
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.3)',
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
  },
  lastWorkoutTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  lastWorkoutInfo: {
    fontSize: 15,
    color: '#8B5CF6',
    marginBottom: 4,
    fontWeight: '600',
  },
  lastWorkoutFocus: {
    fontSize: 13,
    color: '#9CA3AF',
    fontWeight: '500',
  },

  profileSetupButton: {
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: '#374151',
    borderRadius: 16,
    padding: 18,
    margin: 20,
    alignItems: 'center',
  },
  profileSetupText: {
    color: '#9CA3AF',
    fontSize: 16,
    fontWeight: '600',
  },

  // Modern Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#1F1F26',
    borderRadius: 24,
    padding: 28,
    margin: 20,
    borderWidth: 1,
    borderColor: '#374151',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.4,
    shadowRadius: 24,
    elevation: 16,
  },
  profileModalContent: {
    backgroundColor: '#1F1F26',
    borderRadius: 24,
    padding: 28,
    margin: 20,
    maxHeight: '85%',
    borderWidth: 1,
    borderColor: '#374151',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.4,
    shadowRadius: 24,
    elevation: 16,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 24,
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  
  // Modern Input Styles
  todayInput: {
    backgroundColor: '#0F0F14',
    borderWidth: 1.5,
    borderColor: '#374151',
    borderRadius: 16,
    padding: 18,
    fontSize: 16,
    color: '#FFFFFF',
    minHeight: 120,
    textAlignVertical: 'top',
    marginBottom: 24,
    fontWeight: '500',
  },
  todayModalContent: {
    maxHeight: 350,
    marginBottom: 24,
  },
  todayExerciseCard: {
    backgroundColor: '#0F0F14',
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#374151',
  },
  exerciseCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  exerciseCardName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    flex: 1,
  },
  exerciseCardDetails: {
    fontSize: 14,
    color: '#9CA3AF',
    fontWeight: '500',
  },
  addExerciseButton: {
    backgroundColor: '#10B981',
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    marginBottom: 24,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  addExerciseText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },

  // Profile Form Styles
  profileInfoSection: {
    marginBottom: 20,
  },
  profileLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 8,
    marginLeft: 4,
  },
  profileInput: {
    backgroundColor: '#0F0F14',
    borderWidth: 1.5,
    borderColor: '#374151',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  profileValue: {
    fontSize: 16,
    color: '#9CA3AF',
    backgroundColor: '#0F0F14',
    padding: 16,
    borderRadius: 12,
    textTransform: 'capitalize',
    fontWeight: '500',
    borderWidth: 1,
    borderColor: '#374151',
  },
  logoutButton: {
    backgroundColor: '#EF4444',
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 24,
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  logoutButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },

  // Modern Button Styles
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  modalCancelButton: {
    flex: 1,
    backgroundColor: '#374151',
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
  },
  modalSaveButton: {
    flex: 1,
    backgroundColor: '#8B5CF6',
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  modalCancelText: {
    color: '#9CA3AF',
    fontSize: 16,
    fontWeight: '700',
  },
  modalSaveText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },

  // Common Styles
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    paddingTop: 16,
    backgroundColor: '#0F0F14',
  },
  backButton: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(139, 92, 246, 0.1)',
  },
  backButtonText: {
    fontSize: 16,
    color: '#8B5CF6',
    fontWeight: '700',
  },
  screenTitle: {
    fontSize: 32,
    fontWeight: '900',
    color: '#FFFFFF',
    marginBottom: 8,
    letterSpacing: -1,
  },
  screenSubtitle: {
    fontSize: 16,
    color: '#9CA3AF',
    marginBottom: 24,
    fontWeight: '500',
  },

  // Modern Profile Screen
  section: {
    marginBottom: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 16,
    letterSpacing: -0.5,
  },
  sectionDesc: {
    fontSize: 15,
    color: '#9CA3AF',
    marginBottom: 20,
    fontWeight: '500',
  },
  optionsGrid: {
    gap: 12,
  },
  optionCard: {
    backgroundColor: '#1F1F26',
    padding: 20,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#374151',
    alignItems: 'center',
    marginBottom: 12,
  },
  selectedOption: {
    borderColor: '#8B5CF6',
    backgroundColor: 'rgba(139, 92, 246, 0.1)',
  },
  optionIcon: {
    fontSize: 28,
    marginBottom: 12,
  },
  optionLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 4,
  },
  optionDesc: {
    fontSize: 13,
    color: '#9CA3AF',
    textAlign: 'center',
    fontWeight: '500',
  },
  selectedOptionText: {
    color: '#8B5CF6',
  },
  selectedOptionDesc: {
    color: 'rgba(139, 92, 246, 0.8)',
  },

  // Simple Button Styles
  buttonRow: {
    gap: 12,
    marginBottom: 12,
  },
  simpleButton: {
    backgroundColor: '#1F1F26',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1.5,
    borderColor: '#374151',
  },
  selectedButton: {
    backgroundColor: 'rgba(139, 92, 246, 0.2)',
    borderColor: '#8B5CF6',
  },
  buttonText: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '600',
    textAlign: 'center',
  },
  selectedButtonText: {
    color: '#8B5CF6',
    fontWeight: '700',
  },

  // Primary Buttons
  primaryButton: {
    backgroundColor: '#8B5CF6',
    paddingVertical: 20,
    paddingHorizontal: 32,
    borderRadius: 16,
    alignItems: 'center',
    marginHorizontal: 24,
    marginVertical: 16,
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  primaryButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  disabledButton: {
    backgroundColor: '#374151',
    shadowOpacity: 0,
    elevation: 0,
  },

  // Generated Workout Styles
  workoutHeaderStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#1F1F26',
    marginHorizontal: 20,
    marginBottom: 24,
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: '#374151',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  workoutStat: {
    alignItems: 'center',
  },
  workoutStatValue: {
    fontSize: 28,
    fontWeight: '800',
    color: '#8B5CF6',
  },
  workoutStatLabel: {
    fontSize: 13,
    color: '#9CA3AF',
    marginTop: 6,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  workoutFocus: {
    fontSize: 18,
    color: '#10B981',
    textAlign: 'center',
    marginHorizontal: 20,
    marginBottom: 24,
    fontWeight: '700',
  },
  exercisesList: {
    paddingHorizontal: 20,
  },
  exerciseCard: {
    backgroundColor: '#1F1F26',
    borderRadius: 20,
    padding: 24,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#374151',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  exerciseHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  exerciseNumber: {
    fontSize: 18,
    fontWeight: '800',
    color: '#8B5CF6',
    backgroundColor: 'rgba(139, 92, 246, 0.2)',
    width: 36,
    height: 36,
    borderRadius: 12,
    textAlign: 'center',
    lineHeight: 36,
    marginRight: 16,
  },
  exerciseTarget: {
    fontSize: 14,
    color: '#10B981',
    fontWeight: '600',
    textTransform: 'capitalize',
  },
  exerciseStats: {
    alignItems: 'flex-end',
  },
  exerciseStatText: {
    fontSize: 12,
    color: '#9CA3AF',
    marginBottom: 2,
    fontWeight: '500',
  },
  instructions: {
    marginBottom: 16,
  },
  instructionsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  instructionText: {
    fontSize: 14,
    color: '#9CA3AF',
    lineHeight: 22,
    marginBottom: 6,
    fontWeight: '500',
  },
  exerciseFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#374151',
  },
  equipmentText: {
    fontSize: 12,
    color: '#9CA3AF',
    textTransform: 'capitalize',
    fontWeight: '500',
  },
  difficultyText: {
    fontSize: 12,
    color: '#F59E0B',
    fontWeight: '700',
    textTransform: 'capitalize',
  },
  workoutActions: {
    padding: 24,
    paddingTop: 16,
  },

  // Coming Soon Screen
  comingSoonContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
    backgroundColor: '#0F0F14',
  },
  comingSoonIcon: {
    fontSize: 72,
    marginBottom: 24,
  },
  comingSoonTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 16,
    textAlign: 'center',
    letterSpacing: -1,
  },
  comingSoonText: {
    fontSize: 18,
    color: '#9CA3AF',
    textAlign: 'center',
    marginBottom: 32,
    lineHeight: 28,
    fontWeight: '500',
  },

  bottomSpacing: {
    height: 48,
  },
});