import { StyleSheet } from 'react-native';

// ─── Design Tokens ────────────────────────────────────────────────────────────
export const colors = {
  void:      '#050508',
  abyss:     '#080812',
  deep:      '#0b0b16',
  surface:   '#0f0f1c',
  card:      '#131320',
  lift:      '#181828',
  border:    'rgba(255,255,255,0.05)',
  borderHi:  'rgba(59,130,246,0.22)',
  blue:      '#3b82f6',
  blue2:     '#60a5fa',
  blueDim:   'rgba(59,130,246,0.12)',
  blueDark:  '#1e3a8a',
  green:     '#22c55e',
  red:       '#ef4444',
  gold:      '#f59e0b',
  textPri:   '#e0eaff',
  textSec:   '#5a6a9a',
  textDim:   '#2a2a45',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.void,
  },
  flex1: {
    flex: 1,
  },

  // ─── Login Screen ───────────────────────────────────────────────────────────
  loginScrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  loginContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 40,
    backgroundColor: colors.void,
  },
  loginHeader: {
    alignItems: 'center',
    marginBottom: 44,
  },
  loginIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: colors.blueDark,
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: colors.blue,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 20,
    elevation: 10,
  },
  loginIconText: {
    fontSize: 30,
  },
  loginTitle: {
    fontSize: 38,
    fontFamily: 'BebasNeue-Regular',
    color: colors.textPri,
    letterSpacing: 5,
    marginBottom: 6,
  },
  loginTagline: {
    fontSize: 11,
    color: colors.textSec,
    letterSpacing: 3,
    textTransform: 'uppercase',
    fontWeight: '700',
  },
  loginSubtitle: {
    fontSize: 14,
    color: colors.textSec,
    textAlign: 'center',
    fontWeight: '500',
  },
  loginForm: {
    marginBottom: 28,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.blue2,
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 6,
    marginLeft: 2,
  },
  loginInput: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    borderRadius: 14,
    padding: 16,
    fontSize: 15,
    color: colors.textPri,
    fontWeight: '500',
  },
  authButton: {
    backgroundColor: colors.blueDark,
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.25)',
    shadowColor: colors.blue,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 8,
  },
  authButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 1,
    fontFamily: 'BebasNeue-Regular',
  },
  toggleAuthButton: {
    alignItems: 'center',
    paddingVertical: 8,
    marginBottom: 12,
  },
  toggleAuthText: {
    color: colors.blue2,
    fontSize: 14,
    fontWeight: '600',
  },
  forgotPasswordButton: {
    alignItems: 'center',
    marginBottom: 28,
    paddingVertical: 6,
  },
  forgotPasswordText: {
    color: colors.textSec,
    fontSize: 13,
    fontWeight: '600',
  },
  skipSection: {
    marginBottom: 28,
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.textDim,
  },
  dividerText: {
    marginHorizontal: 14,
    color: colors.textSec,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  skipButton: {
    backgroundColor: 'rgba(255,255,255,0.025)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
  },
  skipButtonText: {
    color: colors.textSec,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  loginFooter: {
    alignItems: 'center',
    marginTop: 20,
  },
  footerText: {
    color: colors.textSec,
    fontSize: 12,
    textAlign: 'center',
    lineHeight: 18,
  },

  // ─── Welcome Screen ─────────────────────────────────────────────────────────
  welcomeContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    backgroundColor: colors.void,
  },
  welcomeTitle: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 56,
    color: colors.textPri,
    marginBottom: 8,
    textAlign: 'center',
    letterSpacing: 4,
  },
  welcomeSubtitle: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 24,
    color: colors.blue2,
    marginBottom: 12,
    textAlign: 'center',
    letterSpacing: 3,
  },
  welcomeTagline: {
    fontSize: 12,
    color: colors.textSec,
    letterSpacing: 3,
    textTransform: 'uppercase',
    fontWeight: '700',
    marginBottom: 32,
  },
  welcomeDescription: {
    fontSize: 15,
    color: colors.textSec,
    textAlign: 'center',
    marginBottom: 36,
    lineHeight: 24,
    fontWeight: '500',
  },
  features: {
    marginBottom: 44,
    alignItems: 'center',
  },
  featureText: {
    fontSize: 14,
    color: colors.green,
    marginBottom: 10,
    textAlign: 'center',
    fontWeight: '700',
    letterSpacing: 0.3,
  },

  // ─── Workout Screen Header ───────────────────────────────────────────────────
  workoutHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: 24,
    paddingTop: 16,
    backgroundColor: colors.void,
  },
  profileButton: {
    backgroundColor: colors.blueDim,
    borderRadius: 16,
    width: 52,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.25)',
  },
  profileButtonText: {
    fontSize: 22,
    color: colors.blue2,
  },
  dateText: {
    fontSize: 11,
    color: colors.textSec,
    marginBottom: 4,
    fontWeight: '700',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  welcomeBack: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 32,
    color: colors.textPri,
    letterSpacing: 2,
  },

  // ─── Today's Workout Card ────────────────────────────────────────────────────
  todayCard: {
    backgroundColor: 'rgba(255,255,255,0.025)',
    margin: 20,
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.borderHi,
    shadowColor: colors.blue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 6,
  },
  todayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  todayTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.textPri,
    letterSpacing: 0.3,
  },
  addText: {
    fontSize: 12,
    color: colors.blue2,
    fontWeight: '700',
    backgroundColor: colors.blueDim,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.2)',
  },
  todayContent: {
    fontSize: 14,
    color: colors.textSec,
    lineHeight: 22,
    fontWeight: '500',
  },
  todayExercisesList: {
    marginTop: 14,
  },
  todayExerciseItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(59,130,246,0.06)',
    padding: 14,
    borderRadius: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.14)',
  },
  exerciseInfo: {
    flex: 1,
  },
  exerciseName: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPri,
    marginBottom: 3,
  },
  exerciseDetails: {
    fontSize: 12,
    color: colors.textSec,
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  removeButton: {
    backgroundColor: 'rgba(239,68,68,0.15)',
    borderRadius: 10,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.25)',
  },
  removeButtonText: {
    color: colors.red,
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 20,
  },

  // ─── Main Action Buttons ─────────────────────────────────────────────────────
  mainButtons: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  generateButton: {
    backgroundColor: colors.blueDark,
    borderRadius: 14,
    padding: 14,
    alignItems: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.2)',
    shadowColor: colors.blue,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 8,
  },
  generateIcon: {
    fontSize: 22,
    marginBottom: 6,
  },
  generateButtonText: {
    fontFamily: 'BebasNeue-Regular',
    color: '#fff',
    fontSize: 17,
    letterSpacing: 2,
    marginBottom: 2,
  },
  generateSubtext: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 12,
    fontWeight: '500',
  },
  llmButton: {
    backgroundColor: 'rgba(255,255,255,0.025)',
    borderRadius: 14,
    padding: 12,
    alignItems: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
  },
  llmIcon: {
    fontSize: 18,
    marginBottom: 5,
  },
  llmButtonText: {
    fontFamily: 'BebasNeue-Regular',
    color: colors.textPri,
    fontSize: 16,
    letterSpacing: 1.5,
    marginBottom: 1,
  },
  llmSubtext: {
    color: colors.textSec,
    fontSize: 11,
    fontWeight: '500',
  },
  programsButton: {
    backgroundColor: 'rgba(255,255,255,0.025)',
    borderRadius: 14,
    padding: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
  },
  programsIcon: {
    fontSize: 18,
    marginBottom: 5,
  },
  programsButtonText: {
    fontFamily: 'BebasNeue-Regular',
    color: colors.textPri,
    fontSize: 16,
    letterSpacing: 1.5,
    marginBottom: 1,
  },
  programsSubtext: {
    color: colors.textSec,
    fontSize: 11,
    fontWeight: '500',
  },

  // ─── Stats Cards ─────────────────────────────────────────────────────────────
  quickStats: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginBottom: 22,
    gap: 10,
  },
  statCard: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.02)',
    borderRadius: 16,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.04)',
    minHeight: 72,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  statNumber: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 24,
    color: colors.blue2,
    letterSpacing: 1,
    marginBottom: 3,
  },
  statLabel: {
    fontSize: 9,
    color: colors.textSec,
    textTransform: 'uppercase',
    fontWeight: '700',
    letterSpacing: 1.5,
    textAlign: 'center',
  },

  // ─── Last Workout Card ───────────────────────────────────────────────────────
  lastWorkoutCard: {
    backgroundColor: 'rgba(59,130,246,0.06)',
    margin: 20,
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.18)',
  },
  lastWorkoutTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.textPri,
    marginBottom: 6,
  },
  lastWorkoutInfo: {
    fontSize: 14,
    color: colors.blue2,
    marginBottom: 3,
    fontWeight: '700',
  },
  lastWorkoutFocus: {
    fontSize: 12,
    color: colors.textSec,
    fontWeight: '500',
  },

  profileSetupButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    borderRadius: 14,
    padding: 16,
    margin: 20,
    alignItems: 'center',
  },
  profileSetupText: {
    color: colors.textSec,
    fontSize: 14,
    fontWeight: '600',
  },

  // ─── Modal Styles ─────────────────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: colors.surface,
    borderRadius: 22,
    padding: 26,
    margin: 20,
    borderWidth: 1,
    borderColor: colors.borderHi,
    shadowColor: colors.blue,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.2,
    shadowRadius: 32,
    elevation: 16,
  },
  profileModalContent: {
    backgroundColor: colors.surface,
    borderRadius: 22,
    padding: 26,
    margin: 20,
    maxHeight: '85%',
    borderWidth: 1,
    borderColor: colors.borderHi,
    shadowColor: colors.blue,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.2,
    shadowRadius: 32,
    elevation: 16,
  },
  modalTitle: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 28,
    color: colors.textPri,
    marginBottom: 22,
    textAlign: 'center',
    letterSpacing: 2,
  },

  // ─── Input Styles ─────────────────────────────────────────────────────────────
  todayInput: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    borderRadius: 14,
    padding: 16,
    fontSize: 15,
    color: colors.textPri,
    minHeight: 110,
    textAlignVertical: 'top',
    marginBottom: 20,
    fontWeight: '500',
  },
  todayModalContent: {
    maxHeight: 340,
    marginBottom: 20,
  },
  todayExerciseCard: {
    backgroundColor: colors.deep,
    borderRadius: 14,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  exerciseCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  exerciseCardName: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPri,
    flex: 1,
  },
  exerciseCardDetails: {
    fontSize: 12,
    color: colors.textSec,
    fontWeight: '500',
  },
  addExerciseButton: {
    backgroundColor: 'rgba(34,197,94,0.12)',
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(34,197,94,0.25)',
  },
  addExerciseText: {
    color: colors.green,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0.5,
  },

  // ─── Profile Form ─────────────────────────────────────────────────────────────
  profileInfoSection: {
    marginBottom: 18,
  },
  profileLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.blue2,
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 6,
    marginLeft: 2,
  },
  profileInput: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    color: colors.textPri,
    fontWeight: '500',
  },
  profileValue: {
    fontSize: 14,
    color: colors.textSec,
    backgroundColor: 'rgba(255,255,255,0.02)',
    padding: 14,
    borderRadius: 12,
    textTransform: 'capitalize',
    fontWeight: '500',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  logoutButton: {
    backgroundColor: 'rgba(239,68,68,0.12)',
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 22,
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.25)',
  },
  logoutButtonText: {
    color: colors.red,
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.5,
  },

  // ─── Modal Buttons ────────────────────────────────────────────────────────────
  modalButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  modalCancelButton: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
  },
  modalSaveButton: {
    flex: 1,
    backgroundColor: colors.blueDark,
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.25)',
    shadowColor: colors.blue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 6,
  },
  modalCancelText: {
    color: colors.textSec,
    fontSize: 15,
    fontWeight: '700',
  },
  modalSaveText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.3,
  },

  // ─── Common ───────────────────────────────────────────────────────────────────
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    paddingTop: 16,
    backgroundColor: colors.void,
  },
  backButton: {
    padding: 10,
    borderRadius: 12,
    backgroundColor: colors.blueDim,
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.2)',
  },
  backButtonText: {
    fontSize: 14,
    color: colors.blue2,
    fontWeight: '700',
  },
  screenTitle: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 36,
    color: colors.textPri,
    marginBottom: 6,
    letterSpacing: 2,
  },
  screenSubtitle: {
    fontSize: 13,
    color: colors.textSec,
    marginBottom: 22,
    fontWeight: '500',
  },

  // ─── Profile Screen ───────────────────────────────────────────────────────────
  section: {
    marginBottom: 30,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 24,
    color: colors.textPri,
    marginBottom: 14,
    letterSpacing: 1.5,
  },
  sectionDesc: {
    fontSize: 13,
    color: colors.textSec,
    marginBottom: 18,
    fontWeight: '500',
    lineHeight: 20,
  },
  optionsGrid: {
    gap: 10,
  },
  optionCard: {
    backgroundColor: 'rgba(255,255,255,0.025)',
    padding: 18,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    alignItems: 'center',
    marginBottom: 10,
  },
  selectedOption: {
    borderColor: 'rgba(59,130,246,0.45)',
    backgroundColor: 'rgba(59,130,246,0.08)',
  },
  optionIcon: {
    fontSize: 26,
    marginBottom: 10,
  },
  optionLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPri,
    textAlign: 'center',
    marginBottom: 3,
  },
  optionDesc: {
    fontSize: 12,
    color: colors.textSec,
    textAlign: 'center',
    fontWeight: '500',
  },
  selectedOptionText: {
    color: colors.blue2,
  },
  selectedOptionDesc: {
    color: 'rgba(96,165,250,0.75)',
  },

  // ─── Simple Buttons ───────────────────────────────────────────────────────────
  buttonRow: {
    gap: 10,
    marginBottom: 10,
  },
  simpleButton: {
    backgroundColor: 'rgba(255,255,255,0.025)',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  selectedButton: {
    backgroundColor: 'rgba(59,130,246,0.1)',
    borderColor: 'rgba(59,130,246,0.35)',
  },
  buttonText: {
    fontSize: 15,
    color: colors.textPri,
    fontWeight: '600',
    textAlign: 'center',
  },
  selectedButtonText: {
    color: colors.blue2,
    fontWeight: '800',
  },

  // ─── Primary Buttons ─────────────────────────────────────────────────────────
  primaryButton: {
    backgroundColor: colors.blueDark,
    paddingVertical: 18,
    paddingHorizontal: 28,
    borderRadius: 16,
    alignItems: 'center',
    marginHorizontal: 24,
    marginVertical: 14,
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.25)',
    shadowColor: colors.blue,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 20,
    elevation: 8,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 1,
  },
  disabledButton: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderColor: 'rgba(255,255,255,0.06)',
    shadowOpacity: 0,
    elevation: 0,
  },

  // ─── Generated Workout ────────────────────────────────────────────────────────
  workoutHeaderStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: 'rgba(255,255,255,0.025)',
    marginHorizontal: 20,
    marginBottom: 22,
    borderRadius: 18,
    padding: 22,
    borderWidth: 1,
    borderColor: colors.borderHi,
  },
  workoutStat: {
    alignItems: 'center',
  },
  workoutStatValue: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 30,
    color: colors.blue2,
    letterSpacing: 1,
  },
  workoutStatLabel: {
    fontSize: 10,
    color: colors.textSec,
    marginTop: 4,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  workoutFocus: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 20,
    color: colors.green,
    textAlign: 'center',
    marginHorizontal: 20,
    marginBottom: 22,
    letterSpacing: 2,
  },
  exercisesList: {
    paddingHorizontal: 20,
  },
  exerciseCard: {
    backgroundColor: 'rgba(255,255,255,0.025)',
    borderRadius: 18,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  exerciseHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  exerciseNumber: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 16,
    color: colors.blue2,
    backgroundColor: colors.blueDim,
    width: 34,
    height: 34,
    borderRadius: 10,
    textAlign: 'center',
    lineHeight: 34,
    marginRight: 14,
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.2)',
    letterSpacing: 0.5,
  },
  exerciseTarget: {
    fontSize: 12,
    color: colors.green,
    fontWeight: '700',
    textTransform: 'capitalize',
    letterSpacing: 0.5,
  },
  exerciseStats: {
    alignItems: 'flex-end',
  },
  exerciseStatText: {
    fontSize: 11,
    color: colors.textSec,
    marginBottom: 2,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  instructions: {
    marginBottom: 14,
  },
  instructionsTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.textPri,
    marginBottom: 10,
    letterSpacing: 0.3,
  },
  instructionText: {
    fontSize: 13,
    color: colors.textSec,
    lineHeight: 20,
    marginBottom: 5,
    fontWeight: '500',
  },
  exerciseFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.05)',
  },
  equipmentText: {
    fontSize: 11,
    color: colors.textSec,
    textTransform: 'capitalize',
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  difficultyText: {
    fontSize: 11,
    color: colors.gold,
    fontWeight: '800',
    textTransform: 'capitalize',
    letterSpacing: 0.5,
  },
  workoutActions: {
    padding: 22,
    paddingTop: 14,
  },

  // ─── Coming Soon ──────────────────────────────────────────────────────────────
  comingSoonContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
    backgroundColor: colors.void,
  },
  comingSoonIcon: {
    fontSize: 64,
    marginBottom: 20,
  },
  comingSoonTitle: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 36,
    color: colors.textPri,
    marginBottom: 14,
    textAlign: 'center',
    letterSpacing: 2,
  },
  comingSoonText: {
    fontSize: 16,
    color: colors.textSec,
    textAlign: 'center',
    marginBottom: 28,
    lineHeight: 26,
    fontWeight: '500',
  },

  bottomSpacing: {
    height: 48,
  },
});